### ISSUE TITLE
We do not have a LICENSE file

### ISSUE THREAD

**Issue by anoadragon453** [anoadragon453/busty#11]
What license should we use? I'm not sure it matters all that much, but it's good practice to have one.

https://choosealicense.com/licenses/

I'd probably opt for Apache myself, as it has slightly more commercial limitations than MIT.

**Comment by Cephian** [comment]
I only really know anything in detail about the MIT and GNU licenses, but I'm fine with Apache or really any other reasonable FOSS license you'd prefer

**Comment by anoadragon453** [comment]
In the end I've opted for MIT, as:

1. We're already planning to take content from a MIT-licensed repository: https://github.com/anoadragon453/busty/blob/72e6444e632c59830f04cfd75e3524ea873f3333/emoji_list.py
2. With the Apache license, it's recommended to include a portion of it in each source file... and that inconvenience outweighs the small benefit of the license over MIT for me :P
