### ISSUE TITLE
Autogeneration of Google Forms for Voting

### ISSUE THREAD

**Issue by Cephian** [anoadragon453/busty#12]
It would be convenient if Busty could automatically generate Google Forms for song voting.

From a bit of research, it seems the standard way to do this is to use [Google Apps Script](https://developers.google.com/apps-script/reference/forms). Google Apps Script code is only run remotely on Google Servers and not locally, however scripts can be created and deployed locally through the [REST API](https://developers.google.com/apps-script/api/concepts).

I plan on adding this feature myself, hopefully starting within the next week or so.

**Comment by Cephian** [comment]
A much easier partial implementation of this feature could work like this:

Someone calls `!makeform` on the desired channel, and they are DMed a message with some generated google appscript code and a link to https://script.google.com/home/projects/create. Then to create the form, the user just needs to copy and paste the code and deploy it.

This is much easier than creating the form manually, but also requires no scary things like Google Authentication. Plus, almost no effort implementing this would be wasted if we were to bump it to full automatic creation.

**Comment by anoadragon453** [comment]
@Cephian nice idea! It certainly makes the implementation in the bot much simpler, as well as removes the need to provide credentials to the bot - and allows users to inspect and edit the script beforehand if desired. +1!

**Comment by anoadragon453** [comment]
Some ideas to speed this up. Apparently there's a 3 operation / second rate limit.

- Use the appscript REST API to eliminate the need to create the form manually.
- Instead of using multiple operations for "create question", "set required", "set title", just initially create a question with all the required attributes.


Also we probably don't need to code golf since Discord now supports large text files embedded in messages.

**Comment by anoadragon453** [comment]
https://github.com/anoadragon453/busty/pull/119 goes a ways to making this better, though still takes a few tens of seconds to generate the form. Reducing the number of operations to the form could still help speed this up.

It remains to be seen whether we still want to invest in using the API directly from the bot.
