### ISSUE TITLE
Add a 'preview' command that lets you preview your submission before a bust starts

### ISSUE THREAD

**Issue by anoadragon453** [anoadragon453/busty#144]
Assuming #143 is implemented and we have support for slash commands, it would be nice to have a `/preview` command that everyone could use. One would use `/preview` to submit an audio file and submission text to the busty bot, and the bot would respond with a message that only you can read that shows what your submission will look like when it plays live during a bust.

Most importantly, users can check that their album art will be read correctly and that it looks as they expect. When they are happy with their submission, they submit their track by uploading it to busty's mailbox just as they have always done.

Proposed command syntax:

```
/preview audio:<audio file> <text>
```

an example:

```
/preview audio:<audio file> This is a song I made with my main man @qbert. What a crazy fellow he is. Vocal help from @J. Cole.
```

Discord should pop up a prompt to select a file from your OS for the audio file. I'm hoping it can do so automatically and users won't need to type/select `audio` manually.

Additionally, once #145 is implemented, it'd be nice to include those checks in the output of this command as well.

**Comment by jcogan97** [comment]
Think I'm gonna pick this one up, fellers
