### ISSUE TITLE
Bust playback broken through Discord Stages.

### ISSUE THREAD

**Issue by jcogan97** [anoadragon453/busty#174]
From our previous 2 busty events, we've noticed that the bot will not playback audio inside a Discord Stage when using `/bust`.

As of now, Busty will still join the stage channel but will not throw an error saying "You need to be in a voice channel."
To get around this for now, we have resorted to using normal voice channels to get playback from Busty.

**Comment by anoadragon453** [comment]
This seems to have been related to nextcord failing to include the `ssrc` parameter when sending SPEAKING payloads. https://github.com/nextcord/nextcord/pull/1009 is an upstream PR with a fix.

We'll need to update `requirements.txt` to point to the new nextcord version with the fix once it has been merged and included in a release.

**Comment by jcogan97** [comment]
With the new release version of nextcord 2.4.1, we can close this issue when https://github.com/anoadragon453/busty/pull/178 is merged.
