### ISSUE TITLE
Use rich content to increase message visibility

### ISSUE THREAD

**Issue by anoadragon453** [anoadragon453/busty#2]
The current state of affairs:

![image](https://user-images.githubusercontent.com/1342360/148162284-6fa71788-827a-422b-93a4-81e5a6f20d80.png)

This message was a bit difficult to see amongst the rest of everyone's messages. Ideally we'd make use of Discord's rich message system, which provides some padding around messages, and makes them look more official. Plus we have more options for formatting.

![image](https://user-images.githubusercontent.com/1342360/148162450-9c5e69b7-fedc-4bb4-b5d8-a0b668ada1f2.png)

**Comment by anoadragon453** [comment]
The `!list` command has been converted to use embeds in https://github.com/anoadragon453/busty/pull/18.

It would be nice to also use embeds for:

- [ ] The "Playing: ..." message sent before each song.
- [ ] The "Chilling for X seconds" message sent before each song.
- [ ] The "Thanks for coming" message at the end.

**Comment by Cephian** [comment]
Commit #23 Resolves the "Now Playing" and "Chillin" messages, but I forgot to include the "Thanks for Coming" so I'll leave this issue open for now

**Comment by anoadragon453** [comment]
I think with https://github.com/anoadragon453/busty/pull/29 merged, this is now done :tada:
