### ISSUE TITLE
Some song names are missing

### ISSUE THREAD

**Issue by anoadragon453** [anoadragon453/busty#201]
![image](https://github.com/anoadragon453/busty/assets/1342360/fdbc35c1-7626-414d-95bb-37b7d397dca3)

Presumably due to #200. Might only happen to songs that don't have a title (and the filename is blank).

**Comment by Cephian** [comment]
Fixed in https://github.com/anoadragon453/busty/pull/200/commits/b92100927ace03e0059c22ba5ff10fffb2c6a4da
