### ISSUE TITLE
`!list` command output is not rendered correctly on Discord for Android

### ISSUE THREAD

**Issue by anoadragon453** [anoadragon453/busty#22]
The output of the `!list` command makes use of markdown in its rendering. On desktop/web and iOS platforms, this markdown is rendered correctly. On Discord Android however, markdown does not look to be rendered, and output looks like the following:

![image](https://user-images.githubusercontent.com/1342360/149629784-e9d2e118-a050-49e9-b41e-79fe1376bbd2.png)

whereas it should look more akin to:

![image](https://user-images.githubusercontent.com/1342360/149629797-3e3347cc-5bca-49b3-a010-8c8730c52a6e.png)

@Cephian has reported the bug to Discord. There's not much we can do on our side unless we modify the output of the command to no longer require markdown.

Unfortunately, looking around, this bug looks to have been known [as early as 2019](https://stackoverflow.com/questions/59523219/discord-py-bot-not-using-proper-text-formatting-in-embeds-but-only-on-mobile).

**Comment by anoadragon453** [comment]
@Cephian what do you think about picking a colour for the embed? Mostly just for helping the message stand out even more. For instance, if using red:

![image](https://user-images.githubusercontent.com/1342360/149630049-5d08ab09-b30a-4f85-9e10-ceeb0eb8ab63.png)

One just needs to set the [`discord.Embed.colour`](https://discordpy.readthedocs.io/en/latest/api.html?highlight=member#discord.Embed.colour) attribute (interestingly spelled using British English).

I don't have much of a preference for a specific colour.

**Comment by Cephian** [comment]
A color is a good idea! I propose `dd2e44`, the color of the hearts in the flaming heart emoji. The "Now Playing" color is included for reference

![image](https://user-images.githubusercontent.com/6956898/149632924-60b4cb6b-1d0f-4b84-a4f8-a84afb24fbbe.png)

**Comment by anoadragon453** [comment]
Looks great to me!

**Comment by anoadragon453** [comment]
@Cephian did discord ever get back to you on this

**Comment by Cephian** [comment]
😞

**Comment by anoadragon453** [comment]
This is fixed now that Discord has replaced their Android app with a new UI based on React Native.

![Screenshot_20220805-173243](https://user-images.githubusercontent.com/1342360/183121690-0162682d-a020-4d84-8c60-666b994da371.png)
