### ISSUE TITLE
Long messages sent with submissions crash Busty

### ISSUE THREAD

**Issue by Cephian** [anoadragon453/busty#54]
The maximum amount of characters in a Discord field value is 1024 ([source](https://discord.com/developers/docs/resources/channel#embed-limits)) but the Discord message character limit is 2000. Submitting a song with a "More Info" section over 1024 characters causes Busty to freeze/crash when that song comes up to play.

I propose we just truncate the message to 1024 characters.

**Comment by anoadragon453** [comment]
Truncating (including a `…`) to 1024 characters sounds like the right solution to me.
