### ISSUE TITLE
Temporarily pin "Now playing" message

### ISSUE THREAD

**Issue by Cephian** [anoadragon453/busty#63]
Temporarily pin the "now playing" message for the duration of the song (and unpin it afterwards) so that people can check channel pins and see the cover art and More Info easily at any point. Right now the Now Playing message can be buried quickly when chat is very active.

**Comment by anoadragon453** [comment]
I had concerns about whether this would make the `!list` pinned message(s) jump around while one was viewing them. I haven't tested whether that's a problem yet.
