### ISSUE TITLE
Reset nickname if bot is killed

### ISSUE THREAD

**Issue by Cephian** [anoadragon453/busty#68]
If the busty process is sent a signal to close during a bust, she will ~~leave behind files in the attachments folder that need to be cleaned out manually, as well as~~ keep whatever nickname she had at the time. We should use the [atexit](https://docs.python.org/3/library/atexit.html) module to attempt to revert Busty's nickname and delete files she is tracking before the program ends.

EDIT: We can't use the atexit module, as the discord client event loop is closed before atexit runs. We would probably have to reset the nick through some nextcord event hook.

**Comment by anoadragon453** [comment]
It looks like [nextcord.on_close()](https://docs.nextcord.dev/en/stable/api.html?highlight=exit#nextcord.on_close) could be what we're after.
