### ISSUE TITLE
Update to nextcord 2.0.0a7

### ISSUE THREAD

**Issue by anoadragon453** [anoadragon453/busty#81]
nextcord's put out another alpha release with some bug fixes and new features: https://github.com/nextcord/nextcord/releases/tag/2.0.0a7

We should consider upgrading (and testing that everything still works).

**Comment by Cephian** [comment]
Do we need to explicitly do anything to upgrade? We have`nextcord[voice]>=2.0.0a6` so I think 2.0.0a7 should automatically be downloaded if running `pip install -r requirements.txt` fresh, and you can upgrade an existing installation with `pip install -r requirements.txt --upgrade`

**Comment by anoadragon453** [comment]
@Cephian indeed, we don't explicitly need to do anything. Though while nextcord is in alpha state, we probably should be testing with the same version of the library that the server is running.

Raising the minimum version doesn't actually ensure that either... Perhaps we should pin the dependency?

**Comment by anoadragon453** [comment]
Not pinning hasn't caused us issues yet... (famous last words).

Going to close this for now as it's non-actionable.
